# Generated by Django 3.1 on 2020-08-28 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='names',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='seasons',
        ),
        migrations.AddField(
            model_name='anime',
            name='end_season',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='anime',
            name='english_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='anime',
            name='japanese_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='anime',
            name='short_name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='anime',
            name='start_season',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='anime',
            name='subbed_season',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='anime',
            name='flags',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='anime',
            name='note',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='response',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='responseanime',
            name='expectations',
            field=models.CharField(blank=True, choices=[(None, 'N/A'), ('S', 'Surprise'), ('D', 'Disappointment')], max_length=1),
        ),
        migrations.DeleteModel(
            name='AnimeNames',
        ),
        migrations.DeleteModel(
            name='AnimeSeasons',
        ),
    ]
