# Generated by Django 3.1 on 2020-08-29 22:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_survey_is_ongoing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='year_season',
        ),
        migrations.AddField(
            model_name='anime',
            name='end_year',
            field=models.SmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(1960), django.core.validators.MaxValueValidator(2040)]),
        ),
        migrations.AddField(
            model_name='anime',
            name='start_year',
            field=models.SmallIntegerField(blank=True, default=2020, null=True, validators=[django.core.validators.MinValueValidator(1960), django.core.validators.MaxValueValidator(2040)]),
        ),
        migrations.AddField(
            model_name='anime',
            name='subbed_year',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1960), django.core.validators.MaxValueValidator(2040)]),
        ),
        migrations.AddField(
            model_name='survey',
            name='season',
            field=models.SmallIntegerField(choices=[(0, 'Winter'), (1, 'Spring'), (2, 'Summer'), (3, 'Fall')], default=3),
        ),
        migrations.AddField(
            model_name='survey',
            name='year',
            field=models.SmallIntegerField(default=2020, validators=[django.core.validators.MinValueValidator(1960), django.core.validators.MaxValueValidator(2040)]),
        ),
        migrations.AlterField(
            model_name='anime',
            name='end_season',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Winter'), (1, 'Spring'), (2, 'Summer'), (3, 'Fall')], null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='start_season',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Winter'), (1, 'Spring'), (2, 'Summer'), (3, 'Fall')], default=2, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='subbed_season',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Winter'), (1, 'Spring'), (2, 'Summer'), (3, 'Fall')], null=True),
        ),
    ]
