# Generated by Django 3.1 on 2020-08-29 22:13

import django.core.validators
from django.db import migrations, models
import survey.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20200830_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='end_season',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Winter'), (1, 'Spring'), (2, 'Summer'), (3, 'Fall')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='end_year',
            field=models.SmallIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1960), django.core.validators.MaxValueValidator(2040)]),
        ),
        migrations.AlterField(
            model_name='anime',
            name='start_season',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Winter'), (1, 'Spring'), (2, 'Summer'), (3, 'Fall')], default=survey.models.Anime.get_season, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='start_year',
            field=models.SmallIntegerField(blank=True, default=survey.models.Anime.get_year, null=True, validators=[django.core.validators.MinValueValidator(1960), django.core.validators.MaxValueValidator(2040)]),
        ),
        migrations.AlterField(
            model_name='anime',
            name='subbed_season',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Winter'), (1, 'Spring'), (2, 'Summer'), (3, 'Fall')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='subbed_year',
            field=models.SmallIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1960), django.core.validators.MaxValueValidator(2040)]),
        ),
        migrations.AlterField(
            model_name='survey',
            name='season',
            field=models.SmallIntegerField(choices=[(0, 'Winter'), (1, 'Spring'), (2, 'Summer'), (3, 'Fall')], default=survey.models.Survey.get_relevant_season),
        ),
        migrations.AlterField(
            model_name='survey',
            name='year',
            field=models.SmallIntegerField(default=survey.models.Survey.get_relevant_year, validators=[django.core.validators.MinValueValidator(1960), django.core.validators.MaxValueValidator(2040)]),
        ),
    ]
