# Generated by Django 3.1 on 2020-09-26 13:22

from django.db import migrations, models
import django.db.models.deletion


def copy_name(apps, schema_editor):
    AnimeName = apps.get_model('survey', 'AnimeName')
    Anime = apps.get_model('survey', 'Anime')
    db_alias = schema_editor.connection.alias

    anime_names = []
    for anime in Anime.objects.using(db_alias).all():
        japanese_name = anime.japanese_name
        english_name = anime.english_name
        short_name = anime.short_name

        if len(japanese_name) > 0:
            anime_names.append(AnimeName(
                anime_name_type='JP',
                name=japanese_name,
                official=True,
                anime=anime,
            ))
        if len(english_name) > 0:
            anime_names.append(AnimeName(
                anime_name_type='EN',
                name=english_name,
                official=True,
                anime=anime,
            ))
        if len(short_name) > 0:
            anime_names.append(AnimeName(
                anime_name_type='SH',
                name=short_name,
                official=True,
                anime=anime,
            ))
    
    AnimeName.objects.using(db_alias).bulk_create(anime_names)


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_remove_survey_anime'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime_name_type', models.CharField(choices=[('JP', 'Japanese name'), ('EN', 'English name'), ('SH', 'Short name')], max_length=2)),
                ('name', models.CharField(max_length=128)),
                ('official', models.BooleanField(default=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.anime')),
            ],
        ),
        migrations.RunPython(
            copy_name
        ),
        migrations.RemoveField(
            model_name='anime',
            name='english_name',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='japanese_name',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='short_name',
        ),
    ]
