# Generated by Django 3.1 on 2020-12-16 17:53

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import survey.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_auto_20201212_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=False, quality=80, size=[300, 600], upload_to=survey.models.Image.generate_unique_file_path),
        ),
        migrations.CreateModel(
            name='SurveyAdditionsRemovals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('is_addition', models.BooleanField()),
                ('response_count', models.SmallIntegerField()),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.anime')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey')),
            ],
        ),
    ]
