# Generated by Django 3.1 on 2020-12-27 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0015_auto_20201216_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
