# Generated by Django 3.1 on 2020-12-28 13:53

from django.db import migrations, models
import survey.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0017_auto_20201227_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='file_large',
            field=models.ImageField(default='', upload_to=survey.models.Image.generate_unique_file_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='file_medium',
            field=models.ImageField(editable=False, null=True, upload_to=survey.models.Image.generate_unique_file_path),
        ),
        migrations.AddField(
            model_name='image',
            name='file_small',
            field=models.ImageField(editable=False, null=True, upload_to=survey.models.Image.generate_unique_file_path),
        ),
    ]
