# Generated by Django 3.1 on 2020-12-28 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0018_auto_20201228_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='file',
        ),
    ]
