# Generated by Django 3.1 on 2020-12-28 14:12

from django.db import migrations, models
import survey.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0019_remove_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file_large',
            field=models.ImageField(upload_to=survey.models.generate_unique_image_file_path),
        ),
        migrations.AlterField(
            model_name='image',
            name='file_medium',
            field=models.ImageField(editable=False, null=True, upload_to=survey.models.generate_unique_image_file_path),
        ),
        migrations.AlterField(
            model_name='image',
            name='file_small',
            field=models.ImageField(editable=False, null=True, upload_to=survey.models.generate_unique_image_file_path),
        ),
    ]
