# Generated by Django 3.1 on 2021-01-01 02:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import survey.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime_type', models.CharField(choices=[('TV', 'TV series'), ('ONAS', 'ONA series'), ('BULK', 'Bulk-released series'), ('MV', 'Movie'), ('ONA', 'Original Net Animation (ONA)'), ('OVA', 'Original Video Animation (OVA)'), ('TVSP', 'TV special')], max_length=4)),
                ('flags', models.CharField(blank=True, max_length=4)),
                ('note', models.CharField(blank=True, max_length=50)),
                ('start_year', models.SmallIntegerField(blank=True, default=survey.models.Anime.get_year, null=True, validators=[django.core.validators.MinValueValidator(1960), django.core.validators.MaxValueValidator(2040)])),
                ('start_season', models.SmallIntegerField(blank=True, choices=[(0, 'Winter'), (1, 'Spring'), (2, 'Summer'), (3, 'Fall')], default=survey.models.Anime.get_season, null=True)),
                ('end_year', models.SmallIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1960), django.core.validators.MaxValueValidator(2040)])),
                ('end_season', models.SmallIntegerField(blank=True, choices=[(0, 'Winter'), (1, 'Spring'), (2, 'Summer'), (3, 'Fall')], default=None, null=True)),
                ('subbed_year', models.SmallIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1960), django.core.validators.MaxValueValidator(2040)])),
                ('subbed_season', models.SmallIntegerField(blank=True, choices=[(0, 'Winter'), (1, 'Spring'), (2, 'Summer'), (3, 'Fall')], default=None, null=True)),
            ],
            options={
                'verbose_name_plural': 'anime',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_preseason', models.BooleanField()),
                ('is_ongoing', models.BooleanField(default=False)),
                ('year', models.SmallIntegerField(default=survey.models.Survey.get_relevant_year, validators=[django.core.validators.MinValueValidator(1960), django.core.validators.MaxValueValidator(2040)])),
                ('season', models.SmallIntegerField(choices=[(0, 'Winter'), (1, 'Spring'), (2, 'Summer'), (3, 'Fall')], default=survey.models.Survey.get_relevant_season)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.anime')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyAdditionRemoval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('is_addition', models.BooleanField()),
                ('response_count', models.SmallIntegerField()),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.anime')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey')),
            ],
            options={
                'verbose_name': 'survey addition/removal',
                'verbose_name_plural': 'survey additions & removals',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('file_small', models.ImageField(editable=False, null=True, upload_to=survey.models.generate_unique_image_file_path)),
                ('file_medium', models.ImageField(editable=False, null=True, upload_to=survey.models.generate_unique_image_file_path)),
                ('file_large', models.ImageField(upload_to=survey.models.generate_unique_image_file_path)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.anime')),
            ],
        ),
        migrations.CreateModel(
            name='AnimeResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('watching', models.BooleanField()),
                ('underwatched', models.BooleanField()),
                ('expectations', models.CharField(blank=True, choices=[(None, 'N/A'), ('S', 'Surprise'), ('D', 'Disappointment')], max_length=1)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.anime')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.response')),
            ],
        ),
        migrations.CreateModel(
            name='AnimeName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime_name_type', models.CharField(choices=[('JP', 'Japanese name'), ('EN', 'English name'), ('SH', 'Short name')], max_length=2)),
                ('name', models.CharField(max_length=128)),
                ('official', models.BooleanField(default=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.anime')),
            ],
        ),
    ]
