# Generated by Django 3.1 on 2020-08-27 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime_type', models.CharField(choices=[('TV', 'TV series'), ('MV', 'Movie'), ('ONA', 'Original Net Animation (ONA)'), ('OVA', 'Original Video Animation (OVA)'), ('TVSP', 'TV special'), ('ONAS', 'ONA series'), ('BULK', 'Bulk-released series')], max_length=4)),
                ('flags', models.CharField(max_length=4)),
                ('note', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AnimeNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('japanese_name', models.CharField(max_length=128)),
                ('english_name', models.CharField(max_length=128)),
                ('short_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='AnimeSeasons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=6)),
                ('end', models.CharField(max_length=6)),
                ('subbed_in', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('age', models.IntegerField(blank=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.anime')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_preseason', models.BooleanField()),
                ('season', models.CharField(max_length=6)),
                ('anime', models.ManyToManyField(to='survey.Anime')),
            ],
        ),
        migrations.CreateModel(
            name='ResponseAnime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True)),
                ('underwatched', models.BooleanField()),
                ('expectations', models.CharField(choices=[(None, 'N/A'), ('S', 'Surprise'), ('D', 'Disappointment')], max_length=1)),
                ('anime', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='survey.anime')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.response')),
            ],
        ),
        migrations.AddField(
            model_name='response',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('url', models.URLField()),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.anime')),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='names',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='survey.animenames'),
        ),
        migrations.AddField(
            model_name='anime',
            name='seasons',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='survey.animeseasons'),
        ),
    ]
