# Generated by Django 3.1 on 2021-03-23 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20210323_2332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['-year', '-season', 'is_preseason']},
        ),
    ]
