# Generated by Django 3.1 on 2021-06-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_auto_20210606_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='missinganime',
            old_name='is_read',
            new_name='user_has_read',
        ),
        migrations.AddField(
            model_name='missinganime',
            name='admin_has_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='missinganime',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
