# Generated by Django 3.1 on 2021-06-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_auto_20210609_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='missinganime',
            name='reason',
            field=models.TextField(blank=True),
        ),
    ]
