# Generated by Django 3.1 on 2020-09-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_auto_20200831_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='responseanime',
            name='watching',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
