# Generated by Django 3.1 on 2021-06-17 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_missinganime_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='MtmUserResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_hash', models.BinaryField(max_length=64)),
                ('response', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.response')),
                ('survey', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='survey.survey')),
            ],
        ),
        migrations.AddIndex(
            model_name='mtmuserresponse',
            index=models.Index(fields=['username_hash', 'survey'], name='survey_mtmu_usernam_73ee10_idx'),
        ),
        migrations.AddConstraint(
            model_name='mtmuserresponse',
            constraint=models.UniqueConstraint(fields=('username_hash', 'survey'), name='unique_username_survey'),
        ),
    ]
