# Generated by Django 3.1 on 2020-09-03 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_responseanime_watching'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='anime',
        ),
    ]
