# Generated by Django 3.1 on 2021-06-20 12:40

from django.db import migrations, models
import survey.models

def use_file_large(apps, schema_editor):
    Image = apps.get_model('survey', 'Image')
    db_alias = schema_editor.connection.alias

    image_list = list(Image.objects.using(db_alias).all())
    for image in image_list:
        image.file_original = image.file_large

    Image.objects.using(db_alias).bulk_update(image_list, ['file_original'])


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_auto_20210617_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='file_original',
            field=models.ImageField(default='a.jpg', upload_to=survey.models.generate_unique_image_file_path),
            preserve_default=False,
        ),
        migrations.RunPython(use_file_large),
        migrations.AlterField(
            model_name='image',
            name='file_large',
            field=models.ImageField(editable=False, null=True, upload_to=survey.models.generate_unique_image_file_path),
        ),
    ]
