# Generated by Django 3.1 on 2020-12-07 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_auto_20200926_1522'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResponseAnime',
            new_name='AnimeResponse',
        ),
    ]
