# Generated by Django 3.2.4 on 2021-07-03 19:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc, now


def set_ongoing(apps, schema_editor):
    Survey = apps.get_model('survey', 'Survey')
    db_alias = schema_editor.connection.alias

    survey_list = list(Survey.objects.using(db_alias).all())
    for survey in survey_list:
        current_time = now()
        survey.is_ongoing = survey.opening_time < current_time and current_time < survey.closing_time

class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_auto_20210620_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='closing_time',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 1, 0, 0, 0, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='opening_time',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0, 0, 0, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.RunPython(migrations.RunPython.noop, set_ongoing),
        migrations.RemoveField(
            model_name='survey',
            name='is_ongoing',
        ),
    ]
