# Generated by Django 3.1 on 2020-12-11 23:31

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_auto_20201207_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
        migrations.AddField(
            model_name='image',
            name='file',
            field=django_resized.forms.ResizedImageField(crop=None, default=None, force_format='PNG', keep_meta=True, quality=0, size=[300, 600], upload_to='images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anime',
            name='anime_type',
            field=models.CharField(choices=[('TV', 'TV series'), ('ONAS', 'ONA series'), ('BULK', 'Bulk-released series'), ('MV', 'Movie'), ('ONA', 'Original Net Animation (ONA)'), ('OVA', 'Original Video Animation (OVA)'), ('TVSP', 'TV special')], max_length=4),
        ),
    ]
