# Generated by Django 3.2.5 on 2021-09-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_auto_20210703_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animeresponse',
            name='expectations',
            field=models.CharField(choices=[(None, 'Met expectations / no answer'), ('S', 'Surprise'), ('D', 'Disappointment')], max_length=1, null=True),
        ),
        migrations.RunSQL(
            sql="""
                UPDATE survey_animeresponse
                SET expectations = NULL
                WHERE expectations = '';
            """,
            reverse_sql="""
                UPDATE survey_animeresponse
                SET expectations = ''
                WHERE expectations = NULL;
            """
        ),
    ]
