# Generated by Django 4.0.7 on 2022-09-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_alter_animeresponse_expectations'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mtmuserresponse',
            name='unique_username_survey',
        ),
        migrations.AddIndex(
            model_name='animeresponse',
            index=models.Index(fields=['anime_id', 'response_id'], name='survey_anim_anime_i_05dde6_idx'),
        ),
        migrations.AddConstraint(
            model_name='animeresponse',
            constraint=models.UniqueConstraint(fields=('response_id', 'anime_id'), name='unique__anime_id__response_id'),
        ),
        migrations.AddConstraint(
            model_name='mtmuserresponse',
            constraint=models.UniqueConstraint(fields=('username_hash', 'survey'), name='unique__survey_id__username_hash'),
        ),
        migrations.AddConstraint(
            model_name='survey',
            constraint=models.UniqueConstraint(fields=('year', 'season', 'is_preseason'), name='unique__is_preseason__season__year'),
        ),
    ]
